- name: Create safekeeper group
  group:
    name: safekeeper
    state: present
  become: true

- name: Create safekeeper user
  user:
    name: safekeeper
    groups: safekeeper
    append: yes
    state: present
    home: /storage/safekeeper
  become: true

- name: Create safekeeper data directory
  ansible.builtin.file:
    path: /storage/safekeeper/data
    state: directory
    mode: "0755"
    owner: safekeeper
    group: safekeeper
  become: true

- name: Limit size of journald logs
  lineinfile:
    path: /etc/systemd/journald.conf
    insertafter: '[Journal]'
    line: 'SystemMaxUse=512M'
  become: true

- name: Restart systemd-journald
  ansible.builtin.systemd:
    daemon_reload: yes
    name: systemd-journald
    enabled: yes
    state: restarted
  become: true

- name: Create safekeeper systemd service file
  copy:
    dest: "/etc/systemd/system/safekeeper.service"
    content: |
      [Unit]
      Description=Zenith safekeeper
      After=network.target auditd.service

      [Service]
      Type=simple
      User=safekeeper
      Environment=RUST_BACKTRACE=1 ZENITH_REPO_DIR=/storage/safekeeper/data LD_LIBRARY_PATH=/usr/local/lib
      ExecStart=/usr/local/bin/safekeeper --id {{ sk_id }} -l {{ private_ip }}:6500 --listen-http {{ private_ip }}:7676 -D /storage/safekeeper/data
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=mixed
      KillSignal=SIGINT
      Restart=on-failure
      StandardOutput=null
      StandardError=null
      TimeoutSec=0

      [Install]
      WantedBy=multi-user.target
  tags:
  - binaries
  become: true

- name: Run safekeeper systemd service
  ansible.builtin.systemd:
    daemon_reload: yes
    name: safekeeper
    enabled: yes
    state: restarted
  tags:
  - binaries
  become: true

- name: Download basebackup from compute node
  ansible.posix.synchronize:
    src: "/tmp/basebackup_sync/"
    dest: "/tmp/replica_sync/"
    mode: push
  delegate_to: "{{groups['compute'][0]}}"
  tags:
  - compute_sync

# Create postgres user
- group:
    name: postgres
    state: present
  become: true
  tags:
  - compute_sync

- user:
    name: postgres
    groups: postgres
    shell: /bin/bash
    append: yes
    state: present
    home: /storage
  become: true
  tags:
  - compute_sync

- name: Increase open files
  lineinfile:
    dest: /etc/security/limits.d/cluster.conf
    line: "postgres  soft  nofile  65535"
    state: present
    create: yes
  become: true
  tags:
  - compute_sync

- name: Create pgdata directory
  ansible.builtin.shell: |
    cp -R /tmp/replica_sync /storage/replica_sync
  become: true
  args:
    creates: /storage/replica_sync/
  tags:
  - compute_sync

- name: Fix pgdata permissions
  file:
    path: "/storage/replica_sync"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
    recurse: true
  become: true
  tags:
  - compute_sync

- name: Create config for syncrepl replica
  ansible.builtin.template:
    src: ./postgresql-replica.conf.j2
    dest: "/storage/replica_sync/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  become: true
  tags:
  - compute_sync

- name: Create standby.signal
  ansible.builtin.file:
    path: "/storage/replica_sync/standby.signal"
    state: touch
    mode: "0644"
    owner: postgres
    group: postgres
  become: true
  tags:
  - compute_sync
