- name: Create storage directory
  ansible.builtin.file:
    path: /storage
    state: directory
    mode: "0777"
  become: true

- name: Create a ext4 filesystem on nvme volume
  community.general.filesystem:
    fstype: ext4
    dev: /dev/nvme0n1
  tags:
  - aws-specific
  become: true

- name: Mount nvme storage
  ansible.posix.mount:
    path: /storage
    src: /dev/nvme0n1
    fstype: ext4
    boot: yes
    state: mounted
  tags:
  - aws-specific
  become: true
