- group:
    name: postgres
    state: present
  become: true

- user:
    name: postgres
    groups: postgres
    shell: /bin/bash
    append: yes
    state: present
    home: /var/db/postgres
  become: true

- name: Increase open files
  lineinfile:
    dest: /etc/security/limits.d/cluster.conf
    line: "postgres  soft  nofile  65535"
    state: present
    create: yes
  become: true

# Create several pgdata directories for different scenarios
- name: Create postgres directories structure
  file:
    path: "{{ pg_base }}/{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
    recurse: true
  become: true
  loop:
  - compute
  - compute_local
  - compute_sync

- name: Initdb
  ansible.builtin.shell:
    cmd: runuser -u postgres -- initdb -U zenith_admin --no-instructions --no-sync
  args:
    chdir: "{{ pg_base }}/{{ item }}"
    creates: "{{ pg_base }}/{{ item }}/PG_VERSION"
  environment:
    PGDATA: "{{ pg_base }}/{{ item }}"
  become: true
  loop:
  - compute
  - compute_local
  - compute_sync

- name: Create compute config for safekeepers compute
  ansible.builtin.template:
    src: ./postgresql.conf.j2
    dest: "{{ pg_base }}/compute/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  become: true

- name: Create compute config for syncrepl compute
  ansible.builtin.template:
    src: ./postgresql-main.conf.j2
    dest: "{{ pg_base }}/compute_sync/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  become: true
  tags:
  - compute_sync

- name: Create pg_hba.conf for syncrepl compute
  copy:
    src: ./pg_hba_trust.conf
    dest: "{{ pg_base }}/compute_sync/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  become: true
  tags:
  - compute_sync

- name: Create benchmark scripts
  copy:
    src: ./run_benchmark.sh
    dest: "{{ pg_base }}/{{ item }}/run_benchmark.sh"
    owner: postgres
    group: postgres
    mode: '0755'
  become: true
  loop:
  - compute
  - compute_local
  - compute_sync

- name: Create basebackup for compute_sync
  ansible.builtin.shell: |
    runuser -u postgres -- pg_ctl start -w
    runuser -u postgres -- psql -c "SELECT pg_create_physical_replication_slot('s1');"
    runuser -u postgres -- psql -c "SELECT pg_create_physical_replication_slot('s2');"
    runuser -u postgres -- psql -c "SELECT pg_create_physical_replication_slot('s3');"
    runuser -u postgres -- pg_basebackup -D "/tmp/basebackup_sync"
    runuser -u postgres -- pg_ctl stop -w
  args:
    chdir: "{{ pg_base }}/compute_sync"
    creates: "/tmp/basebackup_sync"
  environment:
    PGDATA: "{{ pg_base }}/compute_sync"
    PGUSER: zenith_admin
    PGDATABASE: postgres
  become: true
  tags:
  - compute_sync

- name: Change permissions for basebackup
  ansible.builtin.shell: |
    sudo chown -R $USER:$USER /tmp/basebackup_sync
  tags:
  - compute_sync
