- name: Ensure dependencies (Debian)
  apt:
    update_cache: yes
    force_apt_get: yes
    autoremove: yes
    pkg:
    - git
    - automake
    - libtool
    - build-essential
    - bison
    - flex
    - libreadline-dev
    - zlib1g-dev
    - libxml2-dev
    - libcurl4-openssl-dev
    - libsystemd-dev
  become: true

- group:
    name: postgres
    state: present
  become: true

- user:
    name: postgres
    groups: postgres
    shell: /bin/bash
    append: yes
    state: present
    home: /var/db/postgres
  become: true

- name: Increase open files
  lineinfile:
    dest: /etc/security/limits.d/cluster.conf
    line: "postgres  soft  nofile  65535"
    state: present
    create: yes
  become: true

# Mount fast storage
- name: Create a ext4 filesystem on nvme volume
  community.general.filesystem:
    fstype: ext4
    dev: /dev/nvme0n1
  tags:
  - aws-specific
  become: true

- name: Mount nvme storage
  ansible.posix.mount:
    path: /var/db/postgres
    src: /dev/nvme0n1
    fstype: ext4
    boot: yes
    state: mounted
  tags:
  - aws-specific
  become: true

# Create several pgdata directories for different scenarios
- name: Create postgres directories structure
  file:
    path: "{{ pg_base }}/{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
    recurse: true
  become: true
  loop:
  - compute
  - compute_local
  - compute_sync

- name: Initdb
  ansible.builtin.shell:
    cmd: runuser -u postgres -- initdb -U zenith_admin --no-instructions --no-sync
  args:
    chdir: "{{ pg_base }}/{{ item }}"
    creates: "{{ pg_base }}/{{ item }}/PG_VERSION"
  environment:
    PGDATA: "{{ pg_base }}/{{ item }}"
  become: true
  loop:
  - compute
  - compute_local
  - compute_sync

- name: Create compute config for safekeepers compute
  ansible.builtin.template:
    src: ./postgresql.conf.j2
    dest: "{{ pg_base }}/compute/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  become: true

- name: Create benchmark scripts
  copy:
    src: ./run_benchmark.sh
    dest: "{{ pg_base }}/{{ item }}/run_benchmark.sh"
    owner: postgres
    group: postgres
    mode: '0755'
  become: true
  loop:
  - compute
  - compute_local
  - compute_sync

