#
# Deploy binaries and all other stuff useful for running performance tests on real-like deployments
#
---

# Common tasks for both safekeepers and compute, such as downloading binaries and installing dependencies
- hosts: all
  vars:
    # If this is true, binaries will be downloaded from the latest stable docker build.
    # If this is false, binaries will be copied from current machine.
    use_docker: true

  tasks:
  # Install dependencies and zenith binaries
  - name: Import common install tasks
    import_tasks: ../common/install.yml
    tags:
    - install

# Create working directory
- hosts: compute

  tasks:
  - name: Prepare storage
    import_tasks: ../compute/storage.yml
    tags:
    - storage

  - name: Test ping
    import_tasks: ../common/ping.yml
    tags:
    - ping

# Create working directory
- hosts: safekeepers

  tasks:
  - name: Prepare storage
    import_tasks: ../safekeepers/storage.yml
    tags:
    - storage

# Test instances performance
- hosts: all

  tasks:
  - name: Test disk perf
    import_tasks: ../common/disk_benchmark.yml
    tags:
    - diskperf

# Deploy test environment
- hosts: compute
  vars:
    pg_base: /var/db/postgres/

  tasks:
  - name: Import compute tasks
    import_tasks: ../compute/deploy.yml

# Deploy test environment
- hosts: safekeepers

  tasks:
  - name: Import safekeepers tasks
    import_tasks: ../safekeepers/deploy.yml
